version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/go/src/gitub.com/alizoubair/go-grpc-server
    container_name: go-grpc-server
    restart: always
    ports:
      - "8792:8792"
    tty: true
    depends_on:
      - postgres
    networks:
      - fullstack
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "go_grpc_server"
    ports:
      - 5432:5432
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge
